//
//  WeatherInteractor.swift
//  WeatherStat
//
//  Created by Le Thanh Hai on 11/23/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit
import ReactiveCocoa
import ReactiveSwift

protocol WeatherInteractorInput {
    func load(request: WeatherRequest)
}

protocol WeatherInteractorOutput: ErrorPresenterInput {
    func present(response: WeatherResponse)
}

class WeatherInteractor: WeatherInteractorInput {
    var output: WeatherInteractorOutput!
    var repository: Repository!
    // MARK: - Business logic
    func load(request: WeatherRequest) {
        self.repository
            .weatherForecast(latitude: request.latitude,
                                        longitude: request.longitude)
            .startWithResult { [weak self] result in
                if let value = result.value {
                    self?.output.present(response: WeatherResponse(weather: value))
                } else {
                    self?.output.presentError(error: "Error when calling service")
                }
        }
    }
}
