//
//  WeatherPresenter.swift
//  WeatherStat
//
//  Created by Le Thanh Hai on 11/23/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol WeatherPresenterInput: ErrorPresenterInput {
    func present(response: WeatherResponse)
}

protocol WeatherPresenterOutput: class, ErrorPresenterOutput {
    func display(viewModel: WeatherViewModel)
}

class WeatherPresenter: WeatherPresenterInput {
    weak var output: WeatherPresenterOutput!
    
    // MARK: - Presentation logic
    func present(response: WeatherResponse) {
        var sections = [SectionModel]()
        
        let weather = response.weather
        var header: AnyObject? = nil
        var items = [AnyObject]()
        
        // Summary and current degree
        if let current = weather.current,
            let summary = current.summary,
            let temp = current.temperature {
            items.append(TitleSubtitleModel(title: summary,
                                            subtitle: String(format: STRING.DEGREE, temp)))
            sections.append(SectionModel(header: nil, items: items))
        }
        
        // Hour value
        header = nil
        items.removeAll()
        let formatter = DateFormatter()
        formatter.dateFormat = "hh"
        if let hours = weather.hourStatus {
            var models = [HourStatModel]()
            hours.forEach { status in
                if let date = status.time {
                    let hour = formatter.string(from: date)
                    var temp = ""
                    if let degree = status.temperature {
                        temp = String(format: STRING.DEGREE, degree)
                    }
                    var icon = ""
                    if let item = status.icon {
                        icon = item
                    }
                    models.append(HourStatModel(title: hour,
                        image: UIImage(named: icon),
                        subtitle: temp))
                }
            }
            header = HourListModel(models: models)
        }
        
        // Show data for day
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "EEEE"
        if let days = weather.dayStatus {
            days.forEach { status in
                var title = ""
                if let time = status.time {
                    title = dateFormatter.string(from: time)
                }
                var high = ""
                if let degree = status.temperatureHigh {
                    high = String(format: STRING.DEGREE, degree)
                }
                var low = ""
                if let degree = status.temperatureLow {
                    low = String(format: STRING.DEGREE, degree)
                }
                var icon = ""
                if let item = status.icon {
                    icon = item
                }
                items.append(DayStatModel(title: title,
                                          image: UIImage(named: icon),
                                          tempHigh: high,
                                          tempLow: low))
            }
        }
        sections.append(SectionModel(header: header, items: items))        
        
        self.output.display(viewModel: WeatherViewModel(models: sections))
    }
    
    func presentError(error: String) {
        self.output.displayError(error: error)
    }
}
