//
//  WeatherPresenter.swift
//  WeatherStat
//
//  Created by Le Thanh Hai on 11/23/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol WeatherPresenterInput: ErrorPresenterInput {
    func present(response: WeatherResponse)
}

protocol WeatherPresenterOutput: class, ErrorPresenterOutput {
    func display(viewModel: WeatherViewModel)
}

class WeatherPresenter: WeatherPresenterInput {
    weak var output: WeatherPresenterOutput!
    
    // MARK: - Presentation logic
    func present(response: WeatherResponse) {
        
    }
    
    func presentError(error: String) {
        self.output.displayError(error: error)
    }
}
