//
//  WeatherConfigurator.swift
//  WeatherStat
//
//  Created by Le Thanh Hai on 11/23/17.
//  Copyright (c) 2017 haile. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter
extension WeatherViewController: WeatherPresenterOutput {
}

extension WeatherInteractor: WeatherViewControllerOutput {
}

extension WeatherPresenter: WeatherInteractorOutput {
}

class WeatherConfigurator {
    // MARK: - Configuration
    class func getController() -> WeatherViewController {
        let viewController = WeatherViewController()
        let router = WeatherRouter()
        router.viewController = viewController
        
        let presenter = WeatherPresenter()
        presenter.output = viewController
        
        let interactor = WeatherInteractor()
        interactor.output = presenter
        interactor.repository = ServerRepository.instance
        
        viewController.output = interactor
        viewController.router = router
        return viewController
    }
}
